### ISSUE TITLE
Lack of documentation for Media Cards

### ISSUE THREAD

**Issue by Sylphias** [GovTechSG/sgds#59]
Media cards are a component feature that are not documented in sgds website.

currently a makeshift documentation exists on 
designsystem.gov.sg/testing/card/

**Comment by weijunyu** [comment]
# Documentation structure
- Card with all forms of content: header, image, body, footer
- Card with .sgds-card-button, whose hover effect imply a click action on the card
- Card with .is-media-card for simple text cards with fixed height meant to be repeated
- Remove .title and .subtitle in the example since they are not related to cards
